### 결정 트리 알고리즘.

In [4]:
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')

wine 데이터 값의 처음 세개의 열은 특성 값, class가 0일 경우에 레드와인, 1일 경우에 화인트 와인

In [5]:
wine.head()

   alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [6]:
#데이터 프레임 각 열이 null 값이 없는지 확인
wine.info()

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   alcohol  6497 non-null   float64
 1   sugar    6497 non-null   float64
 2   pH       6497 non-null   float64
 3   class    6497 non-null   float64
dtypes: float64(4)
memory usage: 203.2 KB

In [7]:
#데이터 특성을 빠르게 알려줌. 
wine.describe()

           alcohol        sugar           pH        class
count  6497.000000  6497.000000  6497.000000  6497.000000
mean     10.491801     5.443235     3.218501     0.753886
std       1.192712     4.757804     0.160787     0.430779
min       8.000000     0.600000     2.720000     0.000000
25%       9.500000     1.800000     3.110000     1.000000
50%      10.300000     3.000000     3.210000     1.000000
75%      11.300000     8.100000     3.320000     1.000000
max      14.900000    65.800000     4.010000     1.000000

In [8]:
data = wine[['alcohol', 'sugar', 'pH']]
target = wine['class']

In [9]:
data.head()

   alcohol  sugar    pH
0      9.4    1.9  3.51
1      9.8    2.6  3.20
2      9.8    2.3  3.26
3      9.8    1.9  3.16
4      9.4    1.9  3.51